#!/bin/sh
#
# probe.sh — one-shot device detection, run ON the Kobo (busybox sh).
#
# Copy it to the device and run it over SSH/telnet (USBNet/KSM), or drop it in
# .adds/espresso and trigger it once. It detects:
#   • framebuffer geometry/rotation (via fbink -e, falling back to sysfs),
#   • the touch-panel input node (/dev/input/eventN),
#   • the wifi interface,
# then writes a device.conf the dashboard reads at startup. It also echoes the
# result so you can eyeball / copy it.
#
# Usage:  sh probe.sh            # detect + write .adds/espresso/device.conf
#         sh probe.sh -          # detect + print only (no write)
set -u

ESPRESSO_DIR="/mnt/onboard/.adds/espresso"
FBINK="$ESPRESSO_DIR/fbink"
OUT="$ESPRESSO_DIR/device.conf"
[ "${1:-}" = "-" ] && OUT=""

echo "== Kobo espresso device probe =="

# --- framebuffer ------------------------------------------------------------
FB_W=""; FB_H=""
if [ -x "$FBINK" ]; then
  # `fbink -e` prints a line like: "... 1080x1440, ... rotate: 2 ..."
  FB_LINE="$("$FBINK" -e 2>/dev/null | tr ',' '\n' | grep -iE '[0-9]+x[0-9]+' | head -1)"
  FB_W="$(echo "$FB_LINE" | grep -oE '[0-9]+x[0-9]+' | head -1 | cut -dx -f1)"
  FB_H="$(echo "$FB_LINE" | grep -oE '[0-9]+x[0-9]+' | head -1 | cut -dx -f2)"
fi
if [ -z "$FB_W" ] && [ -r /sys/class/graphics/fb0/virtual_size ]; then
  FB_W="$(cut -d, -f1 /sys/class/graphics/fb0/virtual_size)"
  FB_H="$(cut -d, -f2 /sys/class/graphics/fb0/virtual_size)"
fi
[ -n "$FB_W" ] || FB_W=1080
[ -n "$FB_H" ] || FB_H=1440
echo "fb-info        : ${FB_W}x${FB_H}"
[ -x "$FBINK" ] && "$FBINK" -e 2>/dev/null | sed 's/^/  fbink: /'

# --- touch input node -------------------------------------------------------
# Pick the input device whose name looks like a touch panel. Aura HD ("dragon")
# uses a zForce IR digitizer; other Kobos use cyttsp/elan/ntx.
TOUCH_DEV=""
for ev in /dev/input/event*; do
  [ -e "$ev" ] || continue
  n="$(basename "$ev")"
  name="$(cat "/sys/class/input/$n/device/name" 2>/dev/null)"
  case "$name" in
    *[Zz]force*|*[Tt]ouch*|*cyttsp*|*[Ee]lan*|*ntx*|*[Dd]igitizer*|*pt860*)
      TOUCH_DEV="$ev"
      echo "touch-inputnode: $ev  ($name)"
      break
      ;;
  esac
done
if [ -z "$TOUCH_DEV" ]; then
  # Fall back to the last event node — on most Kobos the touch panel is highest.
  for ev in /dev/input/event*; do [ -e "$ev" ] && TOUCH_DEV="$ev"; done
  echo "touch-inputnode: $TOUCH_DEV  (guess — name niet herkend)"
fi
echo "  alle input-nodes:"
for ev in /dev/input/event*; do
  [ -e "$ev" ] || continue
  n="$(basename "$ev")"
  echo "    $ev -> $(cat "/sys/class/input/$n/device/name" 2>/dev/null)"
done

# --- wifi interface ---------------------------------------------------------
WIFI=""
if [ -r /proc/net/wireless ]; then
  WIFI="$(awk 'NR>2 {gsub(":","",$1); print $1; exit}' /proc/net/wireless)"
fi
if [ -z "$WIFI" ]; then
  for net in /sys/class/net/*; do
    iface="$(basename "$net")"
    [ "$iface" = "lo" ] && continue
    case "$iface" in eth0|wlan0) WIFI="$iface"; break;; esac
  done
fi
[ -n "$WIFI" ] || WIFI="eth0"
echo "wifi-interface : $WIFI"

# --- emit device.conf -------------------------------------------------------
CONF="# device.conf — generated by probe.sh on $(date 2>/dev/null)
FBINK_BIN=$FBINK
FB_DEV=/dev/fb0
TOUCH_DEV=$TOUCH_DEV
# Touch panel maxima + axis transform. Defaults calibrated on an Aura HD
# (zForce). Verify with: espresso -touchtest  (tap the four corners).
TOUCH_MAX_X=1400
TOUCH_MAX_Y=1025
TOUCH_SWAP_XY=1
TOUCH_INVERT_X=1
TOUCH_INVERT_Y=0
WIFI_IFACE=$WIFI
DATA_DIR=$ESPRESSO_DIR
"

echo
echo "---- device.conf ----"
printf '%s' "$CONF"
echo "---------------------"

if [ -n "$OUT" ]; then
  mkdir -p "$ESPRESSO_DIR"
  printf '%s' "$CONF" > "$OUT" && echo "geschreven: $OUT"
fi
